[package]
name = "zero2prod_axum"
version = "0.1.0"
edition = "2021"

[lib]
name = "zero2prod_axum"
path = "src/lib.rs"

[[bin]]
name = "zero2prod"
path = "src/main.rs"

[dependencies]
axum = "0.6.20"
hyper = "0.14.27"
tokio = { version = "1.32.0", features = ["macros", "rt-multi-thread"] }
tokio-postgres = { version = "0.7.10", features = ["with-uuid-1"] }
postgres-openssl = "0.5.0"
openssl = "0.10.57"
serde = { version = "1.0.186", features = ["derive"] }
config = "0.13.3"
bb8 = "0.8.1"
bb8-postgres = "0.8.1"
uuid = { version = "1.4.1", features = ["v4"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
secrecy = { version = "0.8.0", features = ["serde"] }

# Dev dependencies are used exclusively when running test or examples
# They do not get included in the final application binary!
[dev-dependencies]
reqwest = "0.11.20"

[profile.dev]
opt-level = 3

[profile.dev.package."*"]
opt-level = 3


