[package]
name = "zero2prod_axum"
version = "0.1.0"
edition = "2021"

[lib]
name = "zero2prod_axum"
path = "src/lib.rs"

[[bin]]
name = "zero2prod"
path = "src/main.rs"

[dependencies]
axum = "0.6.20"
hyper = "0.14.27"
tokio = { version = "1.32.0", features = ["macros", "rt-multi-thread", "signal"] }
tokio-postgres = { version = "0.7.10", features = ["with-uuid-1"] }
hyperlocal = "0.8"
clap = { version = "4.3.19", features  = ["derive"] }
# postgres-native-tls = "0.5.0"
serde = { version = "1.0.186", features = ["derive"] }
serde_json = "1.0.107"
config = "0.13.3"
bb8 = "0.8.1"
bb8-postgres = "0.8.1"
uuid = { version = "1.4.1", features = ["v4"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
secrecy = { version = "0.8.0", features = ["serde"] }
validator = "0.16.1"
reqwest = { version = "0.11.20", default-features = false, features = [
    "json",
    "rustls-tls",
] }
wiremock = "0.5.19"

# Dev dependencies are used exclusively when running test or examples
# They do not get included in the final application binary!
[dev-dependencies]
fake = "2.8.0"
rand = "0.8.5"

[profile.dev]
opt-level = 3

[profile.dev.package."*"]
opt-level = 3
