# configuration.yaml
app_port: 8000
# This directory should be created before running server
socket_dir: "/Users/ghashy/Desktop/sockets/"
app_addr: "127.0.0.1"
database:
  host: "127.0.0.1"
  port: 5432
  # If non empty, use unix socket file. Shold be directory with .s.PGSQL.5432 file.
  socket_file: "/tmp"
  username: "ghashy"
  password: "ghashy"
  database_name: "newsletter"
email_client:
  base_url: "https://api.postmarkapp.com"
  sender_email: "test@gmail.com"
  # IMPORTANT: We are only setting the development value,
  # we'll deal with the production token outside of version control
  # (given that it's a sensitive secret!).
  authorization_token: "my_token"
  timeout: 10000
