# configuration.yaml
# App port, addr, unix socket dir
app_port: 8000
app_addr: "127.0.0.1"
app_base_url: "http://127.0.0.1:8000"
email_delivery_service: postmark
database:
  host: "mypg.orb.local"
  port: 5432
  unix_socket: ""
  username: "postgres"
  password: "ghashy"
  database_name: "newsletter"
email_client:
  base_url: "https://api.postmarkapp.com"
  sender_email: "test@gmail.com"
  authorization_token: "my_token"
  timeout: 10000
