# configuration.yaml
# App port, addr, unix socket dir
app_port: 8000
app_addr: "0.0.0.0"
app_base_url: "https://ghashy.ru"
database:
  host: "db"
  port: 5432
  # If non empty, use unix socket file. Shold be directory with .s.PGSQL.5432 file.
  unix_socket: ""
  username: "postgres"
  password: "ghashy"
  database_name: "newsletter"
email_client:
  base_url: "https://api.postmarkapp.com"
  sender_email: "ghashy@ghashy.ru"
  timeout: 10000
